projects:
  zelda-staging:
    enabled: true
    tenant: zelda
    environment: staging 
    description: This the ZELDA staging environment
    repo: https://github.com/musabmasood/zelda-deployments.git
    otherRepos: []
    autosync: true
    autodelete: true
    selfheal: true
    cluster:
      apiServer: local
    namespaces:
    - zelda-staging
    applications:
    - name: wordpress
      cascadeDelete: true
      namespace: zelda-staging
      release: zelda-wp

